name: profit_tracker
description: Daily profit tracker — Firebase + Multi-user
publish_to: 'none'
version: 3.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.1.2
  qr_flutter: ^4.1.0

  # Firebase
  firebase_core: ^2.24.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0

  sqflite: ^2.4.1
  path: ^1.9.1

  # Device Info
  device_info_plus: ^10.1.2

  # AI (Google Gemini REST API — free tier)
  http: ^1.2.0

  # UI / Utils
  intl: ^0.18.1
  fl_chart: ^0.66.2
  cupertino_icons: ^1.0.6

  # PDF & Share
  pdf: ^3.10.7
  printing: ^5.11.0
  share_plus: ^7.2.1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/logo1.png"

  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/logo4.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/