// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdvZcoUL1hXRu2WXVGnGqSkhUK3S7K6dk',
    appId: '1:727808436359:web:b54bca1df9a55921737022',
    messagingSenderId: '727808436359',
    projectId: 'profittracker-2df26',
    authDomain: 'profittracker-2df26.firebaseapp.com',
    storageBucket: 'profittracker-2df26.firebasestorage.app',
    measurementId: 'G-4ERMK35VNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApq1jXV3gyq6c4qWk401ICH7pCScfnN5U',
    appId: '1:727808436359:android:346950fe8ceaf0dc737022',
    messagingSenderId: '727808436359',
    projectId: 'profittracker-2df26',
    storageBucket: 'profittracker-2df26.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdvZcoUL1hXRu2WXVGnGqSkhUK3S7K6dk',
    appId: '1:727808436359:web:bb99b945ccfacb10737022',
    messagingSenderId: '727808436359',
    projectId: 'profittracker-2df26',
    authDomain: 'profittracker-2df26.firebaseapp.com',
    storageBucket: 'profittracker-2df26.firebasestorage.app',
    measurementId: 'G-97BRVCKJSQ',
  );
}
