// lib/main.dart
// FIX: Use firebase_options.dart for proper initialization.
// The "empty reCAPTCHA token" error means Firebase was initialized without
// proper configuration. Solution: use FlutterFire CLI to generate
// firebase_options.dart, then pass it here.
//
// SETUP STEPS (one time only):
//   1. dart pub global activate flutterfire_cli
//   2. flutterfire configure   (in your project root)
//   3. This generates lib/firebase_options.dart automatically
//   4. Then this file works correctly.

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'firebase_options.dart';   // ← generated by flutterfire configure
import 'screens/login_screen.dart';
import 'screens/home_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform, // ← THIS FIXES LOGIN
  );
  runApp(const ProfitTrackerApp());
}

class ProfitTrackerApp extends StatelessWidget {
  const ProfitTrackerApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Profit Tracker',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF1F4E79)),
        useMaterial3: true,
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.white,
          elevation: 0,
          foregroundColor: Color(0xFF1F4E79),
          titleTextStyle: TextStyle(
            color: Color(0xFF1F4E79),
            fontSize: 20,
            fontWeight: FontWeight.bold,
          ),
        ),
        scaffoldBackgroundColor: const Color(0xFFF5F6FA),
      ),
      home: StreamBuilder<User?>(
        stream: FirebaseAuth.instance.authStateChanges(),
        builder: (ctx, snap) {
          if (snap.connectionState == ConnectionState.waiting) {
            return const Scaffold(
              body: Center(child: CircularProgressIndicator()),
            );
          }
          if (snap.hasData && snap.data != null) return const HomeScreen();
          return const LoginScreen();
        },
      ),
    );
  }
}